### ISSUE TITLE
Add more documentation and help texts

### ISSUE THREAD

**Issue by SandraKla** [SandraKla/ShinySurfer_original#4]
-> currently not particularly understandable and user-friendly
-> add a Home Page at the start (currently nothing)
-> also make Upload DATA and ATLAS together 

![start](https://user-images.githubusercontent.com/52706003/98699104-137d6f00-2377-11eb-96be-642408f0b805.png)

**Comment by Fortuna13** [comment]
Add more opportunities to download the data (by svg `Warning: Error in : The orca command-line utility is required for this functionality`)
